# Generated by Django 6.0.1 on 2026-01-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField()),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('current_step', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('theme1', 'Theme 1: Who Is Your Customer?'), ('theme2', 'Theme 2: What Can You Do for Your Customer?'), ('theme3', 'Theme 3: How Does Your Customer Acquire Your Product?'), ('theme4', 'Theme 4: How Do You Make Money?'), ('theme5', 'Theme 5: How Do You Design and Build Your Product?'), ('theme6', 'Theme 6: How Do You Scale?')], max_length=10)),
                ('step_number', models.IntegerField()),
                ('step_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='companies.company')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('company', 'step_number')},
            },
        ),
    ]
